# Preparing the dataset to be used for the baseline experiments

In [1]:
import pandas as pd

### 1- Concatenating the datasets

In [2]:
df_friday1 = pd.read_csv("CIC-IDS-2018-Dataset/Friday-02-03-2018_TrafficForML_CICFlowMeter.csv")
df_friday2 = pd.read_csv("CIC-IDS-2018-Dataset/Friday-16-02-2018_TrafficForML_CICFlowMeter.csv")

/home/tamer/anaconda3/envs/cic-ids-2018/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3444: DtypeWarning: Columns (0,1,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

In [3]:
df_dataset = pd.concat([df_friday1, df_friday2], axis=0, ignore_index=True)

In [4]:
df_dataset

,Dst Port,Protocol,Timestamp,Flow Duration,Tot Fwd Pkts,Tot Bwd Pkts,TotLen Fwd Pkts,TotLen Bwd Pkts,Fwd Pkt Len Max,Fwd Pkt Len Min,...,Fwd Seg Size Min,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label
0,443,6,02/03/2018 08:47:38,141385,9,7,553,3773.0,202,0,...,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Benign
1,49684,6,02/03/2018 08:47:38,281,2,1,38,0.0,38,0,...,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Benign
2,443,6,02/03/2018 08:47:40,279824,11,15,1086,10527.0,385,0,...,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Benign
3,443,6,02/03/2018 08:47:40,132,2,0,0,0.0,0,0,...,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Benign
4,443,6,02/03/2018 08:47:41,274016,9,13,1285,6141.0,517,0,...,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Benign
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2097145,21,6,16/02/2018 10:36:33,3,1,1,0,0,0,0,...,40,0,0.0,0,0,0,0.0,0,0,DoS attacks-SlowHTTPTest
2097146,21,6,16/02/2018 10:36:33,3,1,1,0,0,0,0,...,40,0,0.0,0,0,0,0.0,0,0,DoS attacks-SlowHTTPTest
2097147,21,6,16/02/2018 10:36:33,3,1,1,0,0,0,0,...,40,0,0.0,0,0,0,0.0,0,0,DoS attacks-SlowHTTPTest
2097148,21,6,16/02/2018 10:36:33,5,1,1,0,0,0,0,...,40,0,0.0,0,0,0,0.0,0,0,DoS attacks-SlowHTTPTest
2097149,21,6,16/02/2018 10:36:33,2,1,1,0,0,0,0,...,40,0,0.0,0,0,0,0.0,0,0,DoS attacks-SlowHTTPTest

In [5]:
df_dataset.columns

Index(['Dst Port', 'Protocol', 'Timestamp', 'Flow Duration', 'Tot Fwd Pkts',
       'Tot Bwd Pkts', 'TotLen Fwd Pkts', 'TotLen Bwd Pkts', 'Fwd Pkt Len Max',
       'Fwd Pkt Len Min', 'Fwd Pkt Len Mean', 'Fwd Pkt Len Std',
       'Bwd Pkt Len Max', 'Bwd Pkt Len Min', 'Bwd Pkt Len Mean',
       'Bwd Pkt Len Std', 'Flow Byts/s', 'Flow Pkts/s', 'Flow IAT Mean',
       'Flow IAT Std', 'Flow IAT Max', 'Flow IAT Min', 'Fwd IAT Tot',
       'Fwd IAT Mean', 'Fwd IAT Std', 'Fwd IAT Max', 'Fwd IAT Min',
       'Bwd IAT Tot', 'Bwd IAT Mean', 'Bwd IAT Std', 'Bwd IAT Max',
       'Bwd IAT Min', 'Fwd PSH Flags', 'Bwd PSH Flags', 'Fwd URG Flags',
       'Bwd URG Flags', 'Fwd Header Len', 'Bwd Header Len', 'Fwd Pkts/s',
       'Bwd Pkts/s', 'Pkt Len Min', 'Pkt Len Max', 'Pkt Len Mean',
       'Pkt Len Std', 'Pkt Len Var', 'FIN Flag Cnt', 'SYN Flag Cnt',
       'RST Flag Cnt', 'PSH Flag Cnt', 'ACK Flag Cnt', 'URG Flag Cnt',
       'CWE Flag Count', 'ECE Flag Cnt', 'Down/Up Ratio', 'Pkt Size Avg',
       'Fwd Seg Size Avg', 'Bwd Seg Size Avg', 'Fwd Byts/b Avg',
       'Fwd Pkts/b Avg', 'Fwd Blk Rate Avg', 'Bwd Byts/b Avg',
       'Bwd Pkts/b Avg', 'Bwd Blk Rate Avg', 'Subflow Fwd Pkts',
       'Subflow Fwd Byts', 'Subflow Bwd Pkts', 'Subflow Bwd Byts',
       'Init Fwd Win Byts', 'Init Bwd Win Byts', 'Fwd Act Data Pkts',
       'Fwd Seg Size Min', 'Active Mean', 'Active Std', 'Active Max',
       'Active Min', 'Idle Mean', 'Idle Std', 'Idle Max', 'Idle Min', 'Label'],
      dtype='object')

In [6]:
df_dataset["Label"].unique()

array(['Benign', 'Bot', 'DoS attacks-SlowHTTPTest', 'DoS attacks-Hulk',
       'Label'], dtype=object)

### 2- Removing row with erroneous 'Label' label

In [7]:
# Remove erroneous 'Label' row
df_dataset.drop(df_dataset.loc[df_dataset["Label"] == "Label"].index, inplace=True)

In [8]:
df_dataset

,Dst Port,Protocol,Timestamp,Flow Duration,Tot Fwd Pkts,Tot Bwd Pkts,TotLen Fwd Pkts,TotLen Bwd Pkts,Fwd Pkt Len Max,Fwd Pkt Len Min,...,Fwd Seg Size Min,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label
0,443,6,02/03/2018 08:47:38,141385,9,7,553,3773.0,202,0,...,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Benign
1,49684,6,02/03/2018 08:47:38,281,2,1,38,0.0,38,0,...,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Benign
2,443,6,02/03/2018 08:47:40,279824,11,15,1086,10527.0,385,0,...,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Benign
3,443,6,02/03/2018 08:47:40,132,2,0,0,0.0,0,0,...,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Benign
4,443,6,02/03/2018 08:47:41,274016,9,13,1285,6141.0,517,0,...,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Benign
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2097145,21,6,16/02/2018 10:36:33,3,1,1,0,0,0,0,...,40,0,0.0,0,0,0,0.0,0,0,DoS attacks-SlowHTTPTest
2097146,21,6,16/02/2018 10:36:33,3,1,1,0,0,0,0,...,40,0,0.0,0,0,0,0.0,0,0,DoS attacks-SlowHTTPTest
2097147,21,6,16/02/2018 10:36:33,3,1,1,0,0,0,0,...,40,0,0.0,0,0,0,0.0,0,0,DoS attacks-SlowHTTPTest
2097148,21,6,16/02/2018 10:36:33,5,1,1,0,0,0,0,...,40,0,0.0,0,0,0,0.0,0,0,DoS attacks-SlowHTTPTest
2097149,21,6,16/02/2018 10:36:33,2,1,1,0,0,0,0,...,40,0,0.0,0,0,0,0.0,0,0,DoS attacks-SlowHTTPTest

### 3- Creating "Malicious" label from the "Bot", "DoS attacks-SlowHTTPTest", and "DoS attacks-Hulk" labels

In [9]:
df_dataset.replace(to_replace=["Bot", "DoS attacks-SlowHTTPTest", "DoS attacks-Hulk"], value="Malicious", inplace=True)

In [10]:
df_dataset

,Dst Port,Protocol,Timestamp,Flow Duration,Tot Fwd Pkts,Tot Bwd Pkts,TotLen Fwd Pkts,TotLen Bwd Pkts,Fwd Pkt Len Max,Fwd Pkt Len Min,...,Fwd Seg Size Min,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label
0,443,6,02/03/2018 08:47:38,141385,9,7,553,3773.0,202,0,...,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Benign
1,49684,6,02/03/2018 08:47:38,281,2,1,38,0.0,38,0,...,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Benign
2,443,6,02/03/2018 08:47:40,279824,11,15,1086,10527.0,385,0,...,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Benign
3,443,6,02/03/2018 08:47:40,132,2,0,0,0.0,0,0,...,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Benign
4,443,6,02/03/2018 08:47:41,274016,9,13,1285,6141.0,517,0,...,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Benign
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2097145,21,6,16/02/2018 10:36:33,3,1,1,0,0,0,0,...,40,0,0.0,0,0,0,0.0,0,0,Malicious
2097146,21,6,16/02/2018 10:36:33,3,1,1,0,0,0,0,...,40,0,0.0,0,0,0,0.0,0,0,Malicious
2097147,21,6,16/02/2018 10:36:33,3,1,1,0,0,0,0,...,40,0,0.0,0,0,0,0.0,0,0,Malicious
2097148,21,6,16/02/2018 10:36:33,5,1,1,0,0,0,0,...,40,0,0.0,0,0,0,0.0,0,0,Malicious
2097149,21,6,16/02/2018 10:36:33,2,1,1,0,0,0,0,...,40,0,0.0,0,0,0,0.0,0,0,Malicious

In [11]:
df_dataset["Label"].unique()

array(['Benign', 'Malicious'], dtype=object)

In [12]:
print(df_dataset["Label"].value_counts()[['Benign']].sum())
print(df_dataset["Label"].value_counts()[['Malicious']].sum())

1209156
887993

### 4- Checking "Protocol" values, and creating dummies based on the assumption that the Protocol values are categorical

In [13]:
df_dataset["Protocol"].unique()

array([6, 0, 17, '6', '0', '17'], dtype=object)

In [14]:
# Forcing them to be strings
df_dataset = df_dataset.astype({"Protocol": str})

In [15]:
df_dataset["Protocol"].unique()

array(['6', '0', '17'], dtype=object)

In [16]:
df_dataset = pd.get_dummies(df_dataset, columns=['Protocol'], drop_first=True)

In [17]:
df_dataset

,Dst Port,Timestamp,Flow Duration,Tot Fwd Pkts,Tot Bwd Pkts,TotLen Fwd Pkts,TotLen Bwd Pkts,Fwd Pkt Len Max,Fwd Pkt Len Min,Fwd Pkt Len Mean,...,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label,Protocol_17,Protocol_6
0,443,02/03/2018 08:47:38,141385,9,7,553,3773.0,202,0,61.444444,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Benign,0,1
1,49684,02/03/2018 08:47:38,281,2,1,38,0.0,38,0,19.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Benign,0,1
2,443,02/03/2018 08:47:40,279824,11,15,1086,10527.0,385,0,98.727273,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Benign,0,1
3,443,02/03/2018 08:47:40,132,2,0,0,0.0,0,0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Benign,0,1
4,443,02/03/2018 08:47:41,274016,9,13,1285,6141.0,517,0,142.777778,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Benign,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2097145,21,16/02/2018 10:36:33,3,1,1,0,0,0,0,0.0,...,0.0,0,0,0,0.0,0,0,Malicious,0,1
2097146,21,16/02/2018 10:36:33,3,1,1,0,0,0,0,0.0,...,0.0,0,0,0,0.0,0,0,Malicious,0,1
2097147,21,16/02/2018 10:36:33,3,1,1,0,0,0,0,0.0,...,0.0,0,0,0,0.0,0,0,Malicious,0,1
2097148,21,16/02/2018 10:36:33,5,1,1,0,0,0,0,0.0,...,0.0,0,0,0,0.0,0,0,Malicious,0,1
2097149,21,16/02/2018 10:36:33,2,1,1,0,0,0,0,0.0,...,0.0,0,0,0,0.0,0,0,Malicious,0,1

In [18]:
# making Label column the last column again
df_dataset.insert(len(df_dataset.columns)-1, 'Label', df_dataset.pop('Label'))

In [19]:
df_dataset

,Dst Port,Timestamp,Flow Duration,Tot Fwd Pkts,Tot Bwd Pkts,TotLen Fwd Pkts,TotLen Bwd Pkts,Fwd Pkt Len Max,Fwd Pkt Len Min,Fwd Pkt Len Mean,...,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Protocol_17,Protocol_6,Label
0,443,02/03/2018 08:47:38,141385,9,7,553,3773.0,202,0,61.444444,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,Benign
1,49684,02/03/2018 08:47:38,281,2,1,38,0.0,38,0,19.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,Benign
2,443,02/03/2018 08:47:40,279824,11,15,1086,10527.0,385,0,98.727273,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,Benign
3,443,02/03/2018 08:47:40,132,2,0,0,0.0,0,0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,Benign
4,443,02/03/2018 08:47:41,274016,9,13,1285,6141.0,517,0,142.777778,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,Benign
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2097145,21,16/02/2018 10:36:33,3,1,1,0,0,0,0,0.0,...,0.0,0,0,0,0.0,0,0,0,1,Malicious
2097146,21,16/02/2018 10:36:33,3,1,1,0,0,0,0,0.0,...,0.0,0,0,0,0.0,0,0,0,1,Malicious
2097147,21,16/02/2018 10:36:33,3,1,1,0,0,0,0,0.0,...,0.0,0,0,0,0.0,0,0,0,1,Malicious
2097148,21,16/02/2018 10:36:33,5,1,1,0,0,0,0,0.0,...,0.0,0,0,0,0.0,0,0,0,1,Malicious
2097149,21,16/02/2018 10:36:33,2,1,1,0,0,0,0,0.0,...,0.0,0,0,0,0.0,0,0,0,1,Malicious

### 5- Dropping some columns that may be irrelevant (would require re-analysis)

In [20]:
columns_to_drop = [
    'Dst Port',
    'Timestamp',
    'Fwd PSH Flags',
    'Bwd PSH Flags',
    'Fwd URG Flags',
    'Bwd URG Flags'
]

In [21]:
df_dataset.drop(columns=columns_to_drop, inplace=True)

In [22]:
df_dataset

,Flow Duration,Tot Fwd Pkts,Tot Bwd Pkts,TotLen Fwd Pkts,TotLen Bwd Pkts,Fwd Pkt Len Max,Fwd Pkt Len Min,Fwd Pkt Len Mean,Fwd Pkt Len Std,Bwd Pkt Len Max,...,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Protocol_17,Protocol_6,Label
0,141385,9,7,553,3773.0,202,0,61.444444,87.534438,1460,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,Benign
1,281,2,1,38,0.0,38,0,19.0,26.870058,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,Benign
2,279824,11,15,1086,10527.0,385,0,98.727273,129.392497,1460,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,Benign
3,132,2,0,0,0.0,0,0,0.0,0.0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,Benign
4,274016,9,13,1285,6141.0,517,0,142.777778,183.887722,1460,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,Benign
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2097145,3,1,1,0,0,0,0,0.0,0.0,0,...,0.0,0,0,0,0.0,0,0,0,1,Malicious
2097146,3,1,1,0,0,0,0,0.0,0.0,0,...,0.0,0,0,0,0.0,0,0,0,1,Malicious
2097147,3,1,1,0,0,0,0,0.0,0.0,0,...,0.0,0,0,0,0.0,0,0,0,1,Malicious
2097148,5,1,1,0,0,0,0,0.0,0.0,0,...,0.0,0,0,0,0.0,0,0,0,1,Malicious
2097149,2,1,1,0,0,0,0,0.0,0.0,0,...,0.0,0,0,0,0.0,0,0,0,1,Malicious

### 6- Dropping missing or duplicate values

In [23]:
df_dataset.dropna(inplace=True)

In [24]:
df_dataset

,Flow Duration,Tot Fwd Pkts,Tot Bwd Pkts,TotLen Fwd Pkts,TotLen Bwd Pkts,Fwd Pkt Len Max,Fwd Pkt Len Min,Fwd Pkt Len Mean,Fwd Pkt Len Std,Bwd Pkt Len Max,...,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Protocol_17,Protocol_6,Label
0,141385,9,7,553,3773.0,202,0,61.444444,87.534438,1460,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,Benign
1,281,2,1,38,0.0,38,0,19.0,26.870058,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,Benign
2,279824,11,15,1086,10527.0,385,0,98.727273,129.392497,1460,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,Benign
3,132,2,0,0,0.0,0,0,0.0,0.0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,Benign
4,274016,9,13,1285,6141.0,517,0,142.777778,183.887722,1460,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,Benign
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2097145,3,1,1,0,0,0,0,0.0,0.0,0,...,0.0,0,0,0,0.0,0,0,0,1,Malicious
2097146,3,1,1,0,0,0,0,0.0,0.0,0,...,0.0,0,0,0,0.0,0,0,0,1,Malicious
2097147,3,1,1,0,0,0,0,0.0,0.0,0,...,0.0,0,0,0,0.0,0,0,0,1,Malicious
2097148,5,1,1,0,0,0,0,0.0,0.0,0,...,0.0,0,0,0,0.0,0,0,0,1,Malicious
2097149,2,1,1,0,0,0,0,0.0,0.0,0,...,0.0,0,0,0,0.0,0,0,0,1,Malicious

In [25]:
df_dataset.drop_duplicates(inplace=True)

In [26]:
df_dataset

,Flow Duration,Tot Fwd Pkts,Tot Bwd Pkts,TotLen Fwd Pkts,TotLen Bwd Pkts,Fwd Pkt Len Max,Fwd Pkt Len Min,Fwd Pkt Len Mean,Fwd Pkt Len Std,Bwd Pkt Len Max,...,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Protocol_17,Protocol_6,Label
0,141385,9,7,553,3773.0,202,0,61.444444,87.534438,1460,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,Benign
1,281,2,1,38,0.0,38,0,19.0,26.870058,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,Benign
2,279824,11,15,1086,10527.0,385,0,98.727273,129.392497,1460,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,Benign
3,132,2,0,0,0.0,0,0,0.0,0.0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,Benign
4,274016,9,13,1285,6141.0,517,0,142.777778,183.887722,1460,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,Benign
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2051973,25,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,Malicious
2053073,37,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,Malicious
2055697,112640543,3,0,0,0,0,0,0,0,0,...,0,0,0,56300000,7.778174593,56300000,56300000,0,0,Benign
2056054,41,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,Malicious
2056064,36,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,Malicious

### 7- Checking distribution of labels after dropping missing or duplicate values

* Malicious: 21.267%
* Benign: 78.733%

In [27]:
print(df_dataset["Label"].value_counts()[['Benign']].sum())
print(df_dataset["Label"].value_counts()[['Malicious']].sum())

1073929
290089

### 8- Replacing Benign labels with zeroes and Malicious labels with ones

In [28]:
df_dataset.replace(to_replace="Benign", value=0, inplace=True)
df_dataset.replace(to_replace="Malicious", value=1, inplace=True)

In [29]:
df_dataset

,Flow Duration,Tot Fwd Pkts,Tot Bwd Pkts,TotLen Fwd Pkts,TotLen Bwd Pkts,Fwd Pkt Len Max,Fwd Pkt Len Min,Fwd Pkt Len Mean,Fwd Pkt Len Std,Bwd Pkt Len Max,...,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Protocol_17,Protocol_6,Label
0,141385,9,7,553,3773.0,202,0,61.444444,87.534438,1460,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,0
1,281,2,1,38,0.0,38,0,19.0,26.870058,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,0
2,279824,11,15,1086,10527.0,385,0,98.727273,129.392497,1460,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,0
3,132,2,0,0,0.0,0,0,0.0,0.0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,0
4,274016,9,13,1285,6141.0,517,0,142.777778,183.887722,1460,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2051973,25,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,1
2053073,37,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,1
2055697,112640543,3,0,0,0,0,0,0,0,0,...,0,0,0,56300000,7.778174593,56300000,56300000,0,0,0
2056054,41,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,1
2056064,36,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,1

In [30]:
print(df_dataset["Label"].value_counts()[[0]].sum())
print(df_dataset["Label"].value_counts()[[1]].sum())

1073929
290089

### 9- Saving dataset

In [31]:
df_dataset.to_csv("processed_friday_dataset.csv", index=False)